# Generated by Django 5.2.5 on 2025-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoanalizado',
            name='archivo',
            field=models.FileField(upload_to='analisis/'),
        ),
    ]
