# Generated by Django 5.2.5 on 2025-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_alter_textoanalizado_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoanalizado',
            name='archivo',
            field=models.FileField(upload_to='textos/'),
        ),
    ]
